### ISSUE TITLE
Request for usage: Puzzles used in RSG Chess

### ISSUE THREAD

**Issue by radi-cho** [pip36/chess-puzzles#1]
Hello,
We're the creators of the [RSG Chess](https://github.com/RSG-Group/RSG-Chess-mobile) game platform, and we're writing with the intention to re-use some of the already gathered by you chess puzzles in an upcoming version of our OSS game _([Play Store link](https://play.google.com/store/apps/details?id=com.rsg.chess))_. We plan to mention your project in our readmes and documentation. Feel free to request any other conditions.

Thanks in advance!
Radostin Cholakov

**Comment by pip36** [comment]
Hi. 
Thanks for the message. Feel free to use the puzzles as you wish. It’s not guaranteed this site will stay up, since it’s just a toy project, but more than happy for you to use them. 
Thanks

**Comment by radi-cho** [comment]
Thanks :)
